### ISSUE TITLE
Run tarantool/tarantool CI locally using nektos/act

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool-qa#118]
## Problems

- [x] A problem around the `ContainerCreate()` 5th argument (https://github.com/nektos/act/pull/525)
- [x] Issue: a strategy clause without matrix 'disables' a job (https://github.com/nektos/act/issues/625)
- [x] .gitignore should be ignored for actions (https://github.com/nektos/act/issues/193)
- [x] Write files as user, not root (https://github.com/nektos/act/issues/398)
- [ ] No make, cmake, ... in a medium-size image (`catthehacker/ubuntu:act-20.04`, [repository](https://github.com/catthehacker/docker_images)).

## Thoughts

I would not request adding more tools to `catthehacker/ubuntu:act-20.04` (except, maybe, make), but rather create our own image based on it and place `.actrc` into the tarantool/tarantool repository root. I guess it would be convenient: no manual configuring will be necessary to run our CI locally.

As a side effect, we can reuse this medium sized image for runs on our self-hosted runners and save some disk space / bootstrap time.

Can we just remove [fail-fast: false](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) to eliminate the second problem? I'll cite it's description:

> When set to `true`, GitHub cancels all in-progress jobs if any matrix job fails. Default: `true`.

Whether it has an effect only when `matrix` clause is used (we have no one)? Or it allows the telegram notification action to be run after a test job fail (I would re-verify it)?

**Comment by Totktonada** [comment]
The issues above are closed. I didn't re-check the new behaviour (however I wrote how I would implement it into the issues).

I think there is nothing to track here. If I'll return back to experimenting around act+tarantool and will find more problems, I'll just open another issue or will write an article with workarounds/recipes to tarantool's wiki.
