### ISSUE TITLE
☂️ Keep and provide results for every test that failed in CI [20sp]

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool-qa#298]
Whenever a test has failed in CI, we should save the build artifacts and make them available for download on the dashboard.

### Make sure that artifacts are written for each failed test

- [x] 13sp https://github.com/tarantool/luatest/issues/253
- [x] 2sp #299

### Save and provide artifacts

- [x] ~~3sp https://github.com/tarantool/multivac/issues/94~~
- [x] 3sp https://github.com/tarantool/multivac/issues/116
- [x] 2sp https://github.com/tarantool/multivac/issues/95
