### ISSUE TITLE
github-ci: use MCS hosts as self-runners

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool-qa#92]
Using Github Actions found that Gihub provides for free the following number of hosts:
20 Linux on Ubuntu 18.04: 2 Cores + 7 Gb memory + 4 Gb swap + 85 Gb disk HDD (found in real while in documentation SSD)
5 OSX on VMware: 3 Cores + 14 Gb memory + 210 Gb SSD

In previous we used local number of hosts:
2 Linux on CentOS 7: 80 Cores + 396 Gb memory + HDD
9 Linux on CentOS 7: 24 Cores + 94 Gb memory + HDD
6 OSX (2: 10.14, 2: 10.15, 2: 11.0): 4 Cores + 16 Gb memory + SSD

For now we are going to use MCS VM to increase the resources. Need to do the following:
- [x] Create standalone project in MCS for CI.
- [x] Create single VM with 4 Cores 8 Gb memory on MCS using prepared image with ubuntu 18.04 at
    https://github.com/tarantool/github-actions-environments
- [x] Check the full tests runtime on it for each testing workflow.
    https://github.com/tarantool/tarantool/tree/avtikhon/gh-qa-110-ci-deb-tmp
- [x] Try different VM configuration and collect tests timings.
- [x] Also resolve group of issues to decrease number of needed resources (in trunk / on review):
  - [x] [x] https://github.com/tarantool/tarantool-qa/issues/101 (no docker, run on ubuntu 18.04)
  - [x] [x] https://github.com/tarantool/tarantool-qa/issues/102 (repository cleanup)
  - [x] [x] https://github.com/tarantool/tarantool-qa/issues/103 (port tags re-movement)
  - [x] [x] https://github.com/tarantool/tarantool-qa/issues/104 (use vardir with test-run)
  - [x] [x] https://github.com/tarantool/tarantool-qa/issues/105 (switch off swap on OSX)
  - [x] [ ] https://github.com/tarantool/tarantool-qa/issues/108 (setup self-hosted runners per each workflow)
  - [x] [x] https://github.com/tarantool/tarantool-qa/issues/110 (enable package jobs for ubuntu-20.04)
  - [x] [x] https://github.com/tarantool/tarantool-qa/issues/114 (kill old hanged processes)
- [ ] Create solution for start/stopping of the VM only when test resources are needed. It can be implemented in the following way:
    Always switched on 2 VMs in MCS, first ready for testing and the second to start and stop new instances. It checks each minute if the first VMs is free from testing otherwise it starts more VMs till any of them became free either number of started VMs reaches the given limit. Also it checks when these VMs became free and switches it off except the last one.

| | 2 * Xeon Skylake 4 Gb | 2 * Core Haswell 8 Gb | |
|---|---|---|---|
| - | 11m 20s | 16m 30s | passed |
| + build | 13m 16s | 20m 37s | passed |
| + j1 | 17m 31s | 24m 15s | passed |
| + j10 | 11m 36s | 17m 06s | passed/1 failed |
| + j30 | 12m 37s | 18m 32s | 10/32 failed |

**Comment by kyukhin** [comment]
First stage: we need to have at least one GH runner deployed on MCS infra.
